name: Build

on:
  push:
    branches:
      - main

jobs:
  deploy:
   runs-on: [self-hosted]
   steps:
      - name: Docker login
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Pull Docker Image
        run: |
          echo "Pulling Docker image..."
          sudo docker pull dockerhubadmin419/swiggy-app:latest

      - name: Image Security Scan
        run: |
          echo "Scanning Docker image for vulnerabilities..."
          trivy image dockerhubadmin419/swiggy-app:latest > trivyimagedeploy.txt
        env:
          TRIVY_SEVERITY: CRITICAL,HIGH

      - name: Deploy Docker Container
        run: |
          echo "Deploying Docker container..."
          sudo docker stop swiggy-clone || true
          sudo docker rm swiggy-clone || true
          sudo docker run -d --name swiggy-app -p 3000:3000 dockerhubadmin419/swiggy-app:latest
