name: Build

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: [self-hosted]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: SonarQube Scan
        uses: sonarsource/sonarqube-scan-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

      - name: Install Node.js and Dependencies
        run: |
          node -v
          npm -v
          cd /home/ubuntu/actions-runner/deployment-using-github-actions
          sudo npm install
        shell: bash

      - name: Docker Build and Push
        run: |
          cd /home/ubuntu/actions-runner/deployment-using-github-actions
          docker build -t swiggy-clone .
          docker tag swiggy-clone dockeradmin419/swiggy-app:latest
          docker login -u ${{ secrets.Dockerhub_username }} -p ${{ secrets.Dockerhub_token }}
          docker push dockeradmin419/swiggy-app:latest
        env:
          DOCKER_CLI_ACI: 1
