name: Build

on:
  push:
    branches:
      - main

jobs:
  deploy:
   runs-on: [self-hosted]
   steps:
      - name: Pull Docker Image
        run: |
          echo "Pulling Docker image..."
          docker pull aakibkhan1212/swiggy-clone:latest

      - name: Image Security Scan
        run: |
          echo "Scanning Docker image for vulnerabilities..."
          trivy image aakibkhan1212/swiggy-clone:latest > trivyimagedeploy.txt
        env:
          TRIVY_SEVERITY: CRITICAL,HIGH

      - name: Deploy Docker Container
        run: |
          echo "Deploying Docker container..."
          docker stop swiggy-clone || true
          docker rm swiggy-clone || true
          docker run -d --name swiggy-clone -p 3000:3000 aakibkhan1212/swiggy-clone:latest

      - name: Update kubeconfig
        run: aws eks --region us-east-1 update-kubeconfig --name EKS_CLOUD
        
      - name: Deploy to kubernetes
        run: kubectl apply -f deployment-service.yml2
        
